---
# tasks file for sample-apache

#- name: Create text
#  copy:
#          content: "{{ text }}"
#          dest: ~/var/www/html/index.html 

#- name: create dirs
#  become: yes
#  file:
#          path: /var/www/html
#          state: directory

- name: create apache2
  become: yes
  apt:
          name: apache2
          update_cache: yes
          state: latest

- name: start and enable apache2
  become: yes
  service:
          name: apache2
          state: started
          enabled: yes

- name: create web-page from template
  become: yes
  template:
          src: index.html.j2
          dest: /var/www/html/index.html
  register: index

- name: restart server on file change
  become: yes
  service:
          name: apache2
          state: restarted
          enabled: yes
  when: index.changed
